---
- name: Add tick stack key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  become: yes

- name: add tick stack apt repository
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu bionic stable
    state: present
    update_cache: yes
  become: yes

- name: Add grafana key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  become: yes

- name: add grafana apt repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: yes
  become: yes

# - name: Upgrade all packages to the latest version
#   become: yes
#   apt:
#     name: "*"
#     state: latest
