---
- name: Install Promethius.
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.18.0/alertmanager-0.18.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  become: yes