- name: Install grafana.
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_6.2.5_amd64.deb

- name: Install Prometheus.
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.18.0/alertmanager-0.18.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
