version: 2
jobs:
  test:
    working_directory: ~/training/third_upload
    docker:
      - image: circleci/python:3.6.4
        environment:
          DATABASE_URL: postgresql://justus@localhost/diary?sslmode=disable
          ANSIBLE_HOST_KEY_CHECKING: False
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: justus
          POSTGRES_DB: diary
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip3 install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: |
            pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  publish:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = justo" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            python3 setup.py sdist
      - run:
          name: upload to pypi
          command: |
            python3 -m venv  venv
             . venv/bin/activate
             pip3 install --upgrade pip
            pip3 install twine
            twine upload dist/*
  deploy:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          name: executing ansible to a remote server
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install ansible
            ansible-playbook -i ansible/hosts ansible/provision.yml

Workflows:
  version: 2
  test_publish_deploy:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
