# - name: Create a virtualenv directory
#   file:
#     path: "{{ venv_dir }}"
#     state: directory
#   become: yes
#   become_user: "{{ deployer_user }}"


# - name: Install setup tools
#   pip:
#     name: setuptools
#     executable: pip3

# - name: Install virtualenv via pip
#   pip:
#     name: virtualenv
#     executable: pip3
#   become: yes
#   become_user: root

# - name: Install dependencies
#   pip:
#     requirements: "{{ app_dir }}/requirements.txt"
#     virtualenv: "{{ venv_dir }}"
#     virtualenv_python: python3.6
#   become: yes
#   become_user: "{{ deployer_user }}"

# - name: Create the env file
#   template:
#     src: env.j2
#     dest: "{{ app_dir }}/.env"
#   become: yes
#   become_user: "{{ deployer_user }}"
