# - name: Set up git configuration
#   apt:
#     name: git
#     state: latest
#   become: yes

# - name: Clone/pull the latest code
#   become: yes
#   become_user: "{{ deployer_user }}"
#   git:
#     repo: "https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/justo340/diaryapp.git"
#     dest: "{{ app_dir }}"

# - name: Recursively change ownership of a directory
#   file:
#     path: /home/ubuntu/justo/diaryapp
#     state: directory
#     recurse: yes
#     owner: ubuntu
