- name: start gunicorn
  shell: |
    . /home/ubuntu/justo/envs/diaryapp/bin/activate
    cd /home/ubuntu/justo/diaryapp
    gunicorn --daemon --workers 3 --bind unix:/home/ubuntu/justo/diaryapp/diaryapp.sock diary.wsgi

- name: Recursively change ownership of a directory
  file:
    path: /home/ubuntu/justo/diaryapp
    state: directory
    recurse: yes
  become: yes
  become_user: ubuntu


