
- name: Install nginx
  apt:
   name: nginx
   state: latest
  become: yes

- name: start nginx
  service:
      name: nginx
      state: started

- name: copy the nginx config file
  template:
    src: diary
    dest: /etc/nginx/sites-available/
  become: yes

- name: create symlink
  file:
    src: /etc/nginx/sites-available/diary
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes
  notify:
    - restart nginx


