- name: Install PostgreSQL
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  vars:
    packages:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
  become: yes

- name: Ensure the PostgreSQL service is running
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ensure database is created
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF-8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0
    state: present

- name: Create user and give access
  become: yes
  become_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    encrypted: yes
    priv: ALL
    state: present

