   #Preferable syntax to start .yml file
- name: Installation          # Name of the task to be performed in the destinaton host
  hosts: all
  #host = All -- Incase you have many servers in your ssh.cfg file
  #hosts: localhost
  become: True  #Makes you an user for the remote host
  tasks:      # Tasks to be performed

    - name: add universe repository for bionic
      apt_repository:
        repo: deb http://archive.ubuntu.com/ubuntu bionic universe
        state: present
      when: ansible_distribution_release == 'bionic'

    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        POSTGRES_DB: diary
        POSTGRES_USER: justus
        POSTGRES_PASSWORD: 12345
        packages:
        - htop
        - python3-apt
        - python3-pip
        - build-essential
        - python-setuptools
        - fabric
        - postgresql
        - postgresql-server-dev-all
        - python-dev
        - python-psycopg2
        - python3-venv
        - gunicorn
        - nginx


        state: present
    - name: upgrade pip
      pip: name=pip state=latest

    - name: create directory diaryapp
      file:
        state: directory
        path: diaryapp

    - name: pull project from github
      git:
        repo: 'https://github.com/justo340/diaryapp.git'
        dest: diaryapp

    - name: install virtualenv
      pip: name=virtualenv

    - name: create virtualenv
      command: /usr/local/bin/virtualenv diaryapp/venv

    - name: installing requirements
      pip:
        virtualenv: /home/ubuntu/diaryapp/venv
        requirements: /home/ubuntu/diaryapp/requirements.txt
        virtualenv_python: python3.6

    - name: activate venv and makemigrations
      shell: |
        . /home/ubuntu/diaryapp/venv/bin/activate
        python3 /home/ubuntu/diaryapp/manage.py migrate

    - name: change owner of directory
      file:
        path: /home/ubuntu/diaryapp
        state: directory
        recurse: yes
        owner: ubuntu
    # - name: change owner of the directory
    #   shell:  sudo chown ubuntu:www-data /home/ubuntu/diaryapp/


    # - name: create gunicorn socket file
    #   template:
    #     src: diaryapp.socket
    #     dest: /etc/systemd/system/
    #   become:

    # - name: create portfolio service file
    #   template:
    #     src: diaryapp.service
    #     dest: /etc/systemd/system/
    #   become: yes

    # - name: systemd reread configs
    #   systemd:
    #     daemon_reload: yes
    #   become: yes

    # - name: Create gunicorn socket
    #   systemd:
    #     state: started
    #     name: diaryapp.socket
    #   become: yes

    # - name: Enable diaryapp.socket
    #   systemd:
    #     name: diaryapp.socket
    #     enabled: yes
    #   become: yes

    # - name: enable diaryapp service
    #   systemd:
    #     name: diaryapp
    #     enabled: yes
    #   become: yes

    # - name: Ensure the PostgreSQL service is running
    #   service:
    #     name: postgresql
    #     state: started
    #     enabled: yes

    # - name: Ensure database is created
    #   become: yes
    #   become_user: Postgres
    #   postgresql_db:
    #     name: diary
    #     encoding: UTF-8
    #     lc_collate: en_US.UTF-8
    #     lc_ctype: en_US.UTF-8
    #     template: template0
    #     state: present

    # - name: Create user and give access
    #   become: yes
    #   become_user: postgres
    #   postgresql_user:
    #     db: diary
    #     name: justus
    #     password: '12345'
    #     priv: ALL
    #     state: present

    # - run:
    #   name: start nginx
    #   command: |
    #     systemctl daemon-reload
    #     systemctl start gunicorn
    #       systemctl start nginx


